### ISSUE TITLE
review for the meetup vol.1

### ISSUE THREAD

**Issue by yomotsu** [tokyowebglmeetup/tokyowebglmeetup.github.io#2]
staff

- @allyogilvie
- @edo_m18
- @h_doxas
- @yomotsu

- @kawada_hiroshi
- @mattari_panda
- @nakajmg
- @neotag

attendees: 100 persons

**Comment by neotag** [comment]
これ終わってるのでクローズしちゃいます。
（問題あればReopen おねがいします。）
